#!/bin/bash

ROOT=$(dirname $(readlink -f "$0"))
cd "$ROOT"

BIN="build-binutils-i686-kos/bin"

ln -s "../${BIN}/i686-kos-addr2line"  "bin/addr2line"
ln -s "../${BIN}/i686-kos-ar"         "bin/ar"
ln -s "../${BIN}/i686-kos-as"         "bin/as"
ln -s "../${BIN}/i686-kos-c++"        "bin/c++"
ln -s "../${BIN}/i686-kos-c++filt"    "bin/c++filt"
ln -s "../${BIN}/i686-kos-cpp"        "bin/cpp"
ln -s "../${BIN}/i686-kos-elfedit"    "bin/elfedit"
ln -s "../${BIN}/i686-kos-g++"        "bin/g++"
ln -s "../${BIN}/i686-kos-gcc-6.2.0"  "bin/gcc-6.2.0"
ln -s "../${BIN}/i686-kos-gcc-ar"     "bin/gcc-ar"
ln -s "../${BIN}/i686-kos-gcc-nm"     "bin/gcc-nm"
ln -s "../${BIN}/i686-kos-gcc-ranlib" "bin/gcc-ranlib"
ln -s "../${BIN}/i686-kos-gcc"        "bin/gcc"
ln -s "../${BIN}/i686-kos-gcov-tool"  "bin/gcov-tool"
ln -s "../${BIN}/i686-kos-gcov"       "bin/gcov"
ln -s "../${BIN}/i686-kos-gprof"      "bin/gprof"
ln -s "../${BIN}/i686-kos-ld.bfd"     "bin/ld.bfd"
ln -s "../${BIN}/i686-kos-ld"         "bin/ld"
ln -s "../${BIN}/i686-kos-nm"         "bin/nm"
ln -s "../${BIN}/i686-kos-objcopy"    "bin/objcopy"
ln -s "../${BIN}/i686-kos-objdump"    "bin/objdump"
ln -s "../${BIN}/i686-kos-ranlib"     "bin/ranlib"
ln -s "../${BIN}/i686-kos-readelf"    "bin/readelf"
ln -s "../${BIN}/i686-kos-size"       "bin/size"
ln -s "../${BIN}/i686-kos-strings"    "bin/strings"
ln -s "../${BIN}/i686-kos-strip"      "bin/strip"


#ln -s "${ROOT}/${BIN}/i686-kos-addr2line"  "/usr/local/bin/i686-kos-addr2line"
#ln -s "${ROOT}/${BIN}/i686-kos-ar"         "/usr/local/bin/i686-kos-ar"
#ln -s "${ROOT}/${BIN}/i686-kos-as"         "/usr/local/bin/i686-kos-as"
#ln -s "${ROOT}/${BIN}/i686-kos-c++"        "/usr/local/bin/i686-kos-c++"
#ln -s "${ROOT}/${BIN}/i686-kos-c++filt"    "/usr/local/bin/i686-kos-c++filt"
#ln -s "${ROOT}/${BIN}/i686-kos-cpp"        "/usr/local/bin/i686-kos-cpp"
#ln -s "${ROOT}/${BIN}/i686-kos-elfedit"    "/usr/local/bin/i686-kos-elfedit"
#ln -s "${ROOT}/${BIN}/i686-kos-g++"        "/usr/local/bin/i686-kos-g++"
#ln -s "${ROOT}/${BIN}/i686-kos-gcc-6.2.0"  "/usr/local/bin/i686-kos-gcc-6.2.0"
#ln -s "${ROOT}/${BIN}/i686-kos-gcc-ar"     "/usr/local/bin/i686-kos-gcc-ar"
#ln -s "${ROOT}/${BIN}/i686-kos-gcc-nm"     "/usr/local/bin/i686-kos-gcc-nm"
#ln -s "${ROOT}/${BIN}/i686-kos-gcc-ranlib" "/usr/local/bin/i686-kos-gcc-ranlib"
#ln -s "${ROOT}/${BIN}/i686-kos-gcc"        "/usr/local/bin/i686-kos-gcc"
#ln -s "${ROOT}/${BIN}/i686-kos-gcov-tool"  "/usr/local/bin/i686-kos-gcov-tool"
#ln -s "${ROOT}/${BIN}/i686-kos-gcov"       "/usr/local/bin/i686-kos-gcov"
#ln -s "${ROOT}/${BIN}/i686-kos-gprof"      "/usr/local/bin/i686-kos-gprof"
#ln -s "${ROOT}/${BIN}/i686-kos-ld.bfd"     "/usr/local/bin/i686-kos-ld.bfd"
#ln -s "${ROOT}/${BIN}/i686-kos-ld"         "/usr/local/bin/i686-kos-ld"
#ln -s "${ROOT}/${BIN}/i686-kos-nm"         "/usr/local/bin/i686-kos-nm"
#ln -s "${ROOT}/${BIN}/i686-kos-objcopy"    "/usr/local/bin/i686-kos-objcopy"
#ln -s "${ROOT}/${BIN}/i686-kos-objdump"    "/usr/local/bin/i686-kos-objdump"
#ln -s "${ROOT}/${BIN}/i686-kos-ranlib"     "/usr/local/bin/i686-kos-ranlib"
#ln -s "${ROOT}/${BIN}/i686-kos-readelf"    "/usr/local/bin/i686-kos-readelf"
#ln -s "${ROOT}/${BIN}/i686-kos-size"       "/usr/local/bin/i686-kos-size"
#ln -s "${ROOT}/${BIN}/i686-kos-strings"    "/usr/local/bin/i686-kos-strings"
#ln -s "${ROOT}/${BIN}/i686-kos-strip"      "/usr/local/bin/i686-kos-strip"


